version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: tracebit-mongo
    ports:
      - "27017:27017"
    volumes:
      - tracebit_mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: tracebit-redis
    ports:
      - "6379:6379"

volumes:
  tracebit_mongo_data:
